name: Xamarin CI

on: 
  push

jobs:
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Android Build
      run: |      
        cd Mobile
        nuget restore
        cd Mobile/Mobile.Android
        msbuild Mobile.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
    - name: NUnit tests  
      run: |
        ls 
        cd Mobile/Mobile.Tests
        dotnet test Mobile.Tests.csproj
