name: Xamarin CI

on: 
  push

jobs:
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Android Build
      timeout-minutes: 10
      run: |      
        cd CodeBase
        ls
        #nuget restore
        ls
        cd Mobile
        ls
        cd Mobile.Android
        ls
        msbuild Mobile.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
    - name: XUnit tests  
      timeout-minutes: 10
      run: |
        ls 
        cd Mobile/Mobile.Tests
        dotnet test Mobile.Tests.csproj
